name: phase1
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.13.7
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.16
  firebase_auth: ^0.16.1
  flutter_google_places: ^0.2.5
  geolocator: ^5.3.2+2
  modal_progress_hud: ^0.1.3
  provider: ^4.3.1
  rxdart: ^0.24.1
  geocoder: ^0.2.1
  websafe_svg: ^1.1.0
  datetime_picker_formfield: ^1.0.0
  holding_gesture: ^0.0.3
  carousel_slider: ^2.2.1
  dots_indicator: ^1.2.0
  url_launcher: ^5.0.5
  flutter_launcher_icons: ^0.7.5
  intl: ^0.16.1
  simple_animations: ^2.2.1
  flutter_svg: ^0.18.0
  flushbar: ^1.10.4
  maps_launcher: ^1.2.2+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3


flutter_icons:
  ios: true
  android: "launcher_icon"
  image_path: "assets/logo_svgs/LinkareLink.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

#TODO: DELETE OVERRIDE WHEN FLUTTER RELEASES FiX
#dependency_overrides:
#  flutter_svg: 0.18.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/ui_svgs/road_sign.svg
    - assets/ui_svgs/searching.svg
    - assets/ui_svgs/dood.svg
    - assets/ui_svgs/order.svg
    - assets/ui_svgs/shopping.svg
    - assets/ui_svgs/deli.svg
    - assets/ui_svgs/settings.svg
    - assets/clothing_svgs/clothes.svg
    - assets/clothing_svgs/beanie.svg
    - assets/clothing_svgs/gloves.svg
    - assets/clothing_svgs/hats.svg
    - assets/clothing_svgs/women_underwear.svg
    - assets/clothing_svgs/elastic_waist_pants.svg
    - assets/clothing_svgs/shirt.svg
    - assets/clothing_svgs/socks.svg
    - assets/clothing_svgs/underwear.svg
    - assets/covid-19_response_svg/covid_19.svg
    - assets/covid-19_response_svg/face_shield.svg
    - assets/covid-19_response_svg/tissue_paper.svg
    - assets/covid-19_response_svg/rubbing_alcohol.svg
    - assets/covid-19_response_svg/hand_sanitizer.svg
    - assets/covid-19_response_svg/latex_gloves.svg
    - assets/covid-19_response_svg/mask.svg
    - assets/covid-19_response_svg/wipes.svg
    - assets/hygiene_svgs/hygiene.svg
    - assets/hygiene_svgs/body_soap.svg
    - assets/hygiene_svgs/nail_clipper.svg
    - assets/hygiene_svgs/laundry_detergent.svg
    - assets/hygiene_svgs/shaving_cream.svg
    - assets/hygiene_svgs/deodorant.svg
    - assets/hygiene_svgs/shampoo.svg
    - assets/hygiene_svgs/lip_balm.svg
    - assets/hygiene_svgs/diaper.svg
    - assets/hygiene_svgs/razor.svg
    - assets/hygiene_svgs/bath_towel.svg
    - assets/hygiene_svgs/soap.svg
    - assets/hygiene_svgs/toilet_paper.svg
    - assets/hygiene_svgs/toothbrush.svg
    - assets/hygiene_svgs/toothpaste.svg
    - assets/logo_svgs/LogoName.png
    - assets/logo_svgs/LinkareIcon.png
    - assets/logo_svgs/LinkareLogoNew.png
    - assets/logo_svgs/whitelogofinal2.png
    - assets/logo_svgs/finalithink.png
    - assets/logo_svgs/ShelterConnectLogo.png
    - assets/logo_svgs/CareConnectLogo.png
    - assets/nutrition_svgs/nutrition.svg
    - assets/nutrition_svgs/beans.svg
    - assets/nutrition_svgs/tomatosauce.svg
    - assets/nutrition_svgs/rice.svg
    - assets/nutrition_svgs/pasta.svg
    - assets/nutrition_svgs/groundbeef.svg
    - assets/nutrition_svgs/chicken.svg
    - assets/nutrition_svgs/tuna.svg
    - assets/nutrition_svgs/vegetables.svg
    - assets/nutrition_svgs/fruits.svg
    - assets/nutrition_svgs/bread.svg
    - assets/nutrition_svgs/eggs.svg
    - assets/nutrition_svgs/energy_bar.svg
    - assets/nutrition_svgs/water.svg
    - assets/nutrition_svgs/potato.svg
    - assets/warmth_svgs/warmth.svg
    - assets/warmth_svgs/pillow.svg
    - assets/warmth_svgs/blanket.svg
    - assets/warmth_svgs/bed_sheets.svg
    - assets/warmth_svgs/sleeping_bag.svg
    - assets/warmth_svgs/sleeping_pad.svg
    - assets/other_svgs/other.svg
    - assets/foodgiving.jpeg
    - assets/foodgivingsmaller.png
    - assets/welcome_sequence/icon1.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
